// Removed unused code from formulas.ino

// --- dead formula_update cases (wrote unread *_formula scalars) ---
    // case 3: LFO1toVCF_formula = ...
    // case 5: ADSR3toPWM_formula = ...
    // case 6: LFO1toPWM_formula = ...
    // case 8: ADSR1toVCA_formula = ...
    // case 9: LFO1toDCO_formula = ...
    // case 10: ADSR3toDETUNE1_formula = ...
    // case 11: LFO2toPWM_formula = ...
